//
//  Product.swift
//  LaRedonda
//
//  Created by sergio joel camacho zarco on 07/04/23.
//

import Foundation

struct Product : Identifiable{
    var id = UUID()
    var name : String
    var type : String
    var cepa : String
    var crianza : String
    var presentacion : String
    var descripcion : String
    var vista : String
    var nariz : String
    var boca : String
    var temperatura : String
    var graduacion : String
    var gastronomia : String
    var price : Int
    var imageNames : [String]
}

var tintoList = [
    Product(name: "LA REDONDA TINTO RUBY", type: "tinto", cepa: "Multivarietal", crianza: "S/C", presentacion: "750 ml", descripcion: "Este vino debe su nombre a la cepa Ruby Cabernet, la cual es utilizada en gran porcentaje para su elaboración y es la que proporciona a la vista ese rojo intenso con destellos violáceos, que en conjunto de su brillantez nos hace enamorarnos de él a primera vista.", vista: "Tonos violáceos intensos con destellos rubí", nariz: "Ciruela, higo maduro ligeras notas a membrillo, notas compotadas.", boca: "Suave y persistente con sensación abocada.", temperatura: "8ºC", graduacion: "12%", gastronomia: "Postres con chocolate obscuro, tapas con presencia de queso azul, pizzas de quesos, alitas BBQ.", price: 172 , imageNames: ["TINTO-RUBY-1", "TINTO-RUBY-2", "TINTO-RUBY-3", "TINTO-RUBY-4"]),
    Product(name: "TORO LIBRE MALBEC", type: "tinto", cepa: "Malbec", crianza: "S/C", presentacion: "750 ml", descripcion: "La línea de vinos Toro Libre está creada en defensa de la vida y cuidado animal. Las ganancias de este vino se usarán para proteger a los toros de lidia en México.", vista: "Intenso color violeta con ligeras notas de evolución en rojo cereza.", nariz: "Carácter frutal como fresa y ligeros toques de canela y pimienta.", boca: "Buena acidez con taninos suaves y permanencia media.", temperatura: "15ºC", graduacion: "13.00%", gastronomia: "Cerdo en salsa de pasilla, Tacos de Marlin y Paella Valenciana.", price: 232, imageNames: ["Toro-Libre-Malbec-1", "Toro-Libre-Malbec-2", "Toro-Libre-Malbec-3", "Toro-Libre-Malbec-4"]),
    Product(name: "LIEBRE POR GATO CABERNET SAUVIGNON", type: "tinto", cepa: "Cabernet Sauvignon", crianza: "S/C", presentacion: "750 ml", descripcion: "Los vinos Liebre por Gato te sorprenderán en todos sus aspectos, tonos vivos, aromas intensos y sabores equilibrados; más de lo que un buen paladar pueda esperar, tendrás liebre por gato y no gato por liebre. Además son vinos con causa cuyo propósito es salvar a las liebres que habitan en los viñedos de Querétaro.", vista: "Rojo ciruela con destellos carmesí", nariz: "Intensidad en notas como zarzamora y ligeros toques de cereza y chile poblano", boca: "Entrada intensa con taninos medios y de permanencia media", temperatura: "15ºC", graduacion: "13.00%", gastronomia: "Ravioles a la bolognesa, barbacoa y pizza con pimientos.", price: 233, imageNames: ["Liebre-Gato-Cabernet-1", "Liebre-Gato-Cabernet-2", "Liebre-Gato-Cabernet-3", "Liebre-Gato-Cabernet-4"]),
    Product(name: "SIERRA GORDA CRIANZA", type: "tinto", cepa: "Merlot, Cabernet Sauvignon", crianza: "S/C", presentacion: " 750 ml.", descripcion: "Vino Tinto Sierra Gorda Crianza se integra a la línea premium de Viñedos La Redonda en 2021. En su etiqueta muestra al Cerro de la Media Luna, al ser parte importante de la cadena montañosa de la Sierra Gorda de Querétaro, distintivo de esta línea", vista: "Presenta un color rojo rubí muy intenso, con algunos tonos purpura, de buena limpidez y brillantes.", nariz: " Intenso con aromas a frutos rojos como ciruela, higos, mermeladas, que complementan las notas a hojas de tabaco y vainilla.", boca: "De entrada suave, con un buen equilibrio entre el alcohol y acidez, de taninos aterciopelados, un vino con un final largo y persistente.", temperatura: "18ºC", graduacion: "13.00%", gastronomia: "Chocolates amargos o con altos porcentajes de cacao, ideal para cortes de carne, estofados, lechón, lasaña, embutidos y quesos maduros.", price: 540, imageNames: ["SierraGorga-Crianza-1", "SierraGorga-Crianza-2", "SierraGorga-Crianza-3", "SierraGorga-Crianza-4"])
]
// change crianza to metodo and fermentacion
var espumosoList = [
    Product(name: "LA REDONDA ESPUMOSO DULCE", type: "espumoso", cepa: "Chenin blanc, \nChardonnay, \nTrebbiano", crianza: "Champenoise \n12 meses en botella.", presentacion: "750ml", descripcion: "Vino de suave color amarillo pajizo con ribete verdoso. En nariz se entremezclan los aromas de frutas como manzana y naranja, con notas amieladas y anisadas. Agradable en boca con una concentración media. Magnificas burbujas con buen equilibrio y final refrescante afrutado.", vista: "Amarillo pálido con ribete verdoso, limpio y brillante, con una columna de burbuja media y persistentes, con una perfecta formación de corona en la superficie", nariz: "Mezcla de aromas a fruta como durazno,  manzana y naranja con notas melosas con sutil nota de anís", boca: "Agradable boca con una concentración media. Magnifico comportamiento de las columnas de las burbujas. Buen equilibrio y final refrescante y afrutado. Apreciándose sus características tras 12 meses de reposo en botella. Final en boca con marcadas notas propias de Chenin Blanc.", temperatura: "6°C a 8°C", graduacion: "12.50%", gastronomia: "Amplia versatilidad para postres, incluso en bebidas para coctelería.", price: 301, imageNames: ["EspumosoDulce1", "EspumosoDulce2", "EspumosoDulce3", "EspumosoDulce4"]),
    Product(name: "ORLANDI BLANCO SEMISECO", type: "espumoso", cepa: "Chenin Blanc, Viura y Chardonnay", crianza: "Champenoise, 12 meses en botella.", presentacion: "750ml", descripcion: "Las mejores uvas de Chenin Blanc, Viura y Chardonnay procedentes de Viñedos La Redonda se presentan como la mejor materia prima para la creación de este espumoso que, después de reposar 12 meses en botella, posee una inigualable calidad", vista: "Tonos pajizos con destellos verdosos, limpio y brillante, con una columna de burbujas finas y persistentes, con una perfecta formación de corona en la superficie.", nariz: "Con intensidad aromática media, y ligeras notas frutas blancas.", boca: "Ataque amable en boca, acidez bien estructurada, refrescante, ligeras notas dulces", temperatura: "5ºC a 8ºC", graduacion: "12.00%", gastronomia: " Mousse de cítricos, ceviches o marlin al pastor.", price: 435, imageNames: ["EspumosoSemiSeco1", "EspumosoSemiSeco2", "EspumosoSemiSeco3", "EspumosoSemiSeco4"]),
    Product(name: "ORLANDI ROSADO SEMISECO", type: "espumoso", cepa: "Malbec y Cabernet", crianza: "Champenoise, 12 meses en botella.", presentacion: "750 ml", descripcion: "Delicado, ligeramente dulce, con un suave matiz cremoso que recuerda sus 12 meses de crianza en botella. Estupendo y bien conseguido este espumoso natural de uvas Malbec y Cabernet.", vista: "Tonos rosa frambuesa, limpio y brillante, con una columna de burbujas finas y persistentes, con una perfecta formación de corona en la superficie.", nariz: "Notas a frutos rojos, y ligeras notas florales.", boca: "Ataque medio debido a sus taninos, de acidez bien estructurada, refrescante, confirmando notas a frutos rojos como grosella y ciruela negra.", temperatura: "6ºC a 8ºC", graduacion: "12.50%", gastronomia: "Amplia versatilidad desde postres y gastronomía mexicana debió a la limpidez de la burbuja en boca.", price: 468, imageNames: ["EspumosoRosadoSemiSeco1", "EspumosoRosadoSemiSeco2", "EspumosoRosadoSemiSeco3", "EspumosoRosadoSemiSeco4"]),
    Product(name: "ORLANDI BRUT NATURE", type: "espumoso", cepa: "Chardonnay", crianza: "Champenoise, 24 meses en botella.", presentacion: "750ml", descripcion: "Vino Espumoso Brut Nature elaborado por el método tradicional con uva Chardonnay de Viñedos La Redonda. Por su tiempo de crianza va adquiriendo un carácter muy personal, uniéndose en uno solo con los aromas de levaduras.", vista: "Tonos amarillo pajizo, limpio y brillante, con una columna de burbujas finas y de buena persistencia, con una perfecta formación de corona en la superficie.", nariz: "Notas a frutas blancas maduras, y ligeras notas a bollería.", boca: "Ataque medio con buena acidez bien estructurada, refrescante, confirmando notas a frutas y flores blancas.", temperatura: " 6ºC a 8ºC", graduacion: "11.50%", gastronomia: "Pay de limón, pan de muerto, rosca de reyes, bisquet relleno de queso cottage y mermelada de fresa, pastel de 3 leches o ensalada de frutas.", price: 435, imageNames: ["EspumosBrutNature1", "EspumosBrutNature2", "EspumosBrutNature3", "EspumosBrutNature4"])
]

var blancoList = [
    Product(name: "LA REDONDA BLANCO RUBY", type: "Blanco", cepa: "Multivarietal.", crianza: "S/C", presentacion: "750ml", descripcion: "Este vino representa la inquietud de una nueva generación de viñateros. Aquellos que, al recibir la tradición del oficio familiar, deciden explorar y dar un nuevo valor al terruño ofrecido por una zona casi irrepetible.", vista: "Amarillo paja con reflejos verdosos, ligeros reflejos dorados", nariz: "Fresco con agradables notas vegetales y de frutas exóticas, aromas a plátano, orejón de chabacano, notas de miel y algunos frutos secos.", boca: "Fresco, vivaz con una persistente nota dulce, manteniendo notas frescas y limpias.", temperatura: "8ºC", graduacion: "13.50%", gastronomia: "Tarta de frutas, camarones al coco, pollo en salsa agridulce, pizza hawaiana.", price: 172, imageNames: ["blancoRuby1", "blancoRuby2", "blancoRuby3", "blancoRuby4"]),
    Product(name: "ORLANDI SAUVIGNON BLANC", type: "Blanco", cepa: "Sauvignon Blanc.", crianza: "6 meses en barrica de roble americano", presentacion: "750ml", descripcion: "Una tradición italiana, que hoy es orgullosamente queretana. Vino elaborado exclusivamente con uva Sauvignon Blanc procedente de vides plantadas en Viñedos La Redonda a 1950 m.s.n.m.", vista: " Densidad media, alta, tonos amarillo paja con ligeros tonos dorados brillante", nariz: "Notas cítricas, flores blancas, plátano maduro, frutos secos y ligeras notas a miel marcando bien el paso por barrica", boca: "Ataque fresco, elegante, acidez bien equilibrada", temperatura: "8ºC a 10ºC", graduacion: "12.50%", gastronomia: "Rodajas de fruta como manzana y pera o Quesos frescos.", price: 292, imageNames: ["SauvignonBlanc1", "SauvignonBlanc2", "SauvignonBlanc3", "SauvignonBlanc4"]),
    Product(name: "ORLANDI MOSCATEL COSECHA TARDÍA", type: "Blanco", cepa: "Moscatel, cosecha tardía", crianza: "6 meses barrica americana.", presentacion: "375ml.", descripcion: "Vino dulce elaborado únicamente a partir de la variedad moscatel de cosecha tardía y fortificado después de fermentación, cuenta con 06 meses de crianza en barrica de roble americano.", vista: "Tonos dorado intenso.", nariz: "Amplia complejidad aromática debido a sus procesos desde cosecha producción y crianza.", boca: "Untuoso y persistente.", temperatura: "6ºC a 8ºC", graduacion: "18.00%", gastronomia: "Perfecto digestivo o acompañante de postres.", price: 352, imageNames: ["moscatel1", "moscatel2", "moscatel3", "moscatel4"]),
    Product(name: "SIERRA LUNA BLANCO", type: "Blanco", cepa: "Sauvignon blanc.", crianza: "6 meses en barrica de roble americano", presentacion: "750 ml.", descripcion: "Es un vino con principios biodinámicos, inspirados en la luna este vino marca sus procesos de cosecha, puesta en barrica y embotellado con plenilunio.", vista: "Tono amarillo dorado, limpio y brillante.", nariz: "Notas tostadas y frutos secos", boca: "Ataque medio alto, de acidez media, untuoso", temperatura: "8ºC", graduacion: "13.00%", gastronomia: "Pescados ligeros o pastas cremosas.", price: 543, imageNames: ["SierraLunaBlanc1", "SierraLunaBlanc2", "SierraLunaBlanc3", "SierraLunaBlanc4"])
]

var roseList = [
    Product(name: "ORLANDI SHIRAZ ROSÉ", type: "rose", cepa: "Syrah.", crianza: "S/C", presentacion: "750ml", descripcion: "Un gran rosado, elaborado con el mosto flor de los mejores racimos de Syrah, afrutado, potente, sabroso y de bello color. Además, muy versátil a la hora de acompañar distintos platos gracias a su gran complejidad, potencia y estructura.", vista: "Tonos Cereza.", nariz: "Notas a frutas rojas, frambuesa y grosella ligeras notas cítricas y de flores como las violetas, algunas compotas.", boca: "Ataque fresco y equilibrado entre el tanino medio y acidez. Persistencia agradable.", temperatura: "6ºC a 8ºC", graduacion: "12.50%", gastronomia: "Frutos como zarzamoras y frambuesa, tacos al pastor, sushi, charcutería o quesos enchilados.", price: 363, imageNames: ["Shiraz-Rose-1", "Shiraz-Rose-2", "Shiraz-Rose-3", "Shiraz-Rose-4"]),
    
    Product(name: "LA REDONDA ROSADO RUBY", type: "rose", cepa: "Multivarietal.", crianza: "S/C", presentacion: "750ml", descripcion: "Es un gran vino para los paladares más jóvenes, destaca su esplendor que produce en la copa y su incomparable textura.", vista: "Rosa franco, ligeramente salmón", nariz: "Notas de cereza y ciruela.", boca: "Dulce equilibrado con una buena acidez, agradable y persistente.", temperatura: "7ºC a 9ºC", graduacion: "11.00%", gastronomia: "Sushi, pizza carnes ligeras, helados cremosos de frutos rojos.", price: 172, imageNames: ["ROSADO-RUBY-1", "ROSADO-RUBY-2", "ROSADO-RUBY-3", "ROSADO-RUBY-4"])

]
